### ISSUE TITLE
Afficher le plan cadastral

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/editeur-bal#138]
Couche de données optionnelle qui permet un meilleur repérage, en particulier lorsque la photographie aérienne et le fond OSM ne sont pas à jour.

**Comment by jdesboeufs** [comment]
On pourrait aussi ajouter les pseudo-numéros et mettre en surbrillance les parcelles qui contiennent une habitation.

**Comment by tmerlier** [comment]
Ajouter par la PR #187
