### ISSUE TITLE
Chargement long

### ISSUE THREAD

**Issue by ValentinGratz** [etalab/editeur-bal#179]
Bonjour,

Je signale qu'il est impossible d’accéder au contenu du site, je ne vois que le bouton "créer une liste", et ensuite, au dessus, il est toujours en train de charger sans rien afficher.

**Comment by jdesboeufs** [comment]
Bonjour,

À ma connaissance il n'y a pas de bouton "Créer une liste".
Pouvez-vous préciser si c'est encore d'actualité ?
