### ISSUE TITLE
Impossible de supprimer une BAL

### ISSUE THREAD

**Issue by MaelREBOUX** [etalab/editeur-bal#183]
Bonjour,

J'ai crée une BAL de test / démo.
Autant on peut supprimer une commune dans une BAL, autant on ne peut pas supprimer la BAL entière.
En tout cas : je n'ai accès à aucun bouton permettant de réaliser cette action.
Dans la fenêtre ci-dessous on s'attend à une image 3 petits points horizontaux à droite, comme dans les autres fenêtres.

![capture_214](https://user-images.githubusercontent.com/6370443/84522553-2233fd00-acd7-11ea-962a-c53c8479655c.png)

![capture_215](https://user-images.githubusercontent.com/6370443/84522673-5efff400-acd7-11ea-855e-d5ddff960c95.png)

**Comment by tmerlier** [comment]
Il est possible de supprimer une BAL depuis la liste de vos BAL (page d'accueil de l'éditeur).

Cependant, par sécurité, l'option de suppression n'est visible que si une BAL est en `Brouillon`. Sur votre capture d'écran, celle-ci à la statut `Prête à être publiée`, il  n'est donc pas possible de la supprimer. 

Vous pouvez revenir au mode `Brouillon` en cliquant sur `Publication` puis sur `Revenir au brouillon`.

**Comment by MaelREBOUX** [comment]
OK. Mais que je n'ai plus accès à ma base BAL : erreur 404 

https://editeur.adresse.data.gouv.fr/bal/5ee1fc37d93c102787de9031

@jdesboeufs l'a pê supprimée entre-temps ?
