### ISSUE TITLE
Remplacer la carte en arrière-plan de l'éditeur

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/editeur-bal#214]
Lorsque l'utilisateur n'est pas dans une BAL, la fenêtre qui s'affiche a toujours un fond de carte vectoriel en arrière-plan.
C'est inutile et gourmand.
Il faudrait le remplacer par quelque chose de statique et surtout moins lourd.

**Comment by GllmR** [comment]
Fait dans #217
