### ISSUE TITLE
Impossible de publier une BAL comportant plusieurs communes

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/editeur-bal#220]
Lorsqu'un utilisateur a mis en place une BAL couvrant plusieurs communes, il est invité à publié sa BAL via le bouton "Publier".
S'il clique sur ce bouton, il est redirigé vers l'interface de publication, qui va produire une erreur 500.
En effet le système de publication actuel n'est prévu que pour une BAL contenant une unique commune.

Il faudrait qu'un clic sur ce bouton affiche une fenêtre d'information qui sera différente si la BAL comporte une commune ou plusieurs.

S'il y a plusieurs communes, il faut suggérer de nous contacter sur adresse@data.gouv.fr en indiquant l'URL de la BAL.

![image (7)](https://user-images.githubusercontent.com/1231232/95429112-37016400-094a-11eb-8bbe-35c2d06c65de.png)

**Comment by GllmR** [comment]
Il serait également pertinent d'ajouter un message d'erreur si l'utilisateur essaye de publier une base adresse vide.
