### ISSUE TITLE
Assigner un lieu-dit à un numéro

### ISSUE THREAD

**Issue by tmerlier** [etalab/editeur-bal#244]
Il est possible d'ajouter un complément d'adresse sur une voie, mais pas sur un numéro. 

Hors une voie peut traverser plusieurs lieux-dits, il serait alors plus adapté d'attribuer le lieu-dit au numéro plutôt que la voie. Cela permettrait de conserver une indication géographique/historique, parfois utile.

**Comment by juliencarnot** [comment]
Je confirme le besoin en tant qu'élu, l'impossibilité de définir un complément d'adresse sur un ou **des** numéros (2 à 3 maisons peuvent partager un lieu dit, ce qui empêche d'en faire une voie/toponyme dans l'éditeur car dans ce cas pas de numéros) risque fort de nous bloquer dans la démarche, alors que cela peut constituer un élément de permanence dans l'adresse et une aide spatiale dans le cas de voies longues de plusieurs kilomètres, traversant plusieurs lieux-dits.

**Comment by juliencarnot** [comment]
Bonjour,
Avez-vous une idée du calendrier pour cette fonctionnalité en production?
Merci d'avance!

**Comment by tmerlier** [comment]
Après quelques rebondissements, la fonctionnalité est enfin en production.
