### ISSUE TITLE
Placer le numéro créé au centre de l'écran en cours

### ISSUE THREAD

**Issue by C-Sophie** [etalab/editeur-bal#276]
Lorsque l'on créée un numéro, il se trouve placé au centre de la commune dézoomée et non au centre de l'écran affiché au moment de la création. Une perte de temps en cas de commune vaste, avec des hameaux écartés par exemple. Il faudrait que le numéro soit créé au centre de l'écran affiché (du zoom en cours) pour ne pas avoir à dézoomer, retrouver l'épingle et revenir sur la voie.

**Comment by tmerlier** [comment]
Ce problème ne semble plus exister.
