### ISSUE TITLE
Modification d'adresse non validée: l'adresse éditée suivante prend le numéro de l'adresse non validée

### ISSUE THREAD

**Issue by juliencarnot** [etalab/editeur-bal#283]
Quand on a déplacé une adresse mais pas bien cliqué sur Modifier (oublié ou clic pas pris en compte) et qu'on clique sur une autre adresse pour la modifier à son tour, la première reprend sa place initiale et la seconde prend le numéro de la première, ce qui est un peu déstabilisant les premières fois... Constaté sous firefox 83. 
![Peek 18-12-2020 11-54](https://user-images.githubusercontent.com/3848493/102607054-f1ba9900-4127-11eb-9dae-499c8a720306.gif)

**Comment by tmerlier** [comment]
Merci pour le signalement @juliencarnot 🙏
