### ISSUE TITLE
Ajouter plusieurs positions à un numéro

### ISSUE THREAD

**Issue by tmerlier** [etalab/editeur-bal#287]
Fonctionnalité de plus en plus demandée, notamment dans les régions montagneuse où l'entrée peut être éloignée de plusieurs centaine de mètres de la délivrance postale par exemple.

**Comment by juliencarnot** [comment]
Je confirme que les cas existent et que cette info peut-être pertinente pour l'organisation de tournées... Je ne m'en suis pas trop préoccupé jusque là, en privilégiant la position entrée, mais si on peut facilement distinguer graphiquement et filtrer les types de positions, ça serait utile. Reste par contre à savoir ce qui est fait à la publication ou par les acteurs hors Poste et livraisons si une commune crée une position délivrance postale mais pas l'entrée correspondante par exemple (oubli ou mauvaise compréhension)...
