### ISSUE TITLE
Modifier la popup de publication

### ISSUE THREAD

**Issue by tmerlier** [etalab/editeur-bal#288]
Modifier le texte de la popup de publication afin d'encourager les utilisateurs à publier leurs adresses au fur et à mesure de leur progression et faire comprendre qu'ils doivent continuer leur adressage sur la même BAL.

Exemple de texte:
```
Félicitations, vous y êtes presque :tada:
Votre Base Adresse Locale est maintenant Prête à être publiée
Vous pouvez dès maintenant publier vos adresses. Vous n’êtes pas obligé d’attendre d’avoir mis à jour l’intégralité de vos adresses. Vous améliorez ainsi de nombreuses adresses sans délais puisque votre Base Adresse Locale est synchronisée chaque jour avec la Base Adresse Nationale. Il vous suffira d'ouvrir à nouveau votre Base Adresse Locale publiée pour l’avancer.
Une seule Base Adresse Locale est publiée par commune : il est conseillé de vérifier laquelle publier et ultérieurement de travailler sur la base publiée sans en créer de nouvelle.
Télécharger vos adresses au format CSV.
```

**Comment by juliencarnot** [comment]
Humm, je n'avais pas conscience de cette option. Peut-être que le guide pourrait suggérer de commencer par corriger les données existantes (numéro mal placé, voie mal orthographiée, éventuellement ajout de numéro attribué mais manquant) puis faire une première publication, avant d'ajouter des voies et des numéros nouveaux (ce qui nécessite com et engagement du conseil). Dans notre cas, ça aurait permis de corriger rapidement quelques aberrations.

Mais dans ce cas, comment savoir si la base publiée peut-être considérée comme complète et à jour? Ça semble être une info utile pour la commune elle même (une BAL a été publiée en 2020, mais était-elle complète?) et les utilisateurs de la donnée, et aussi pour connaître la qualité de la BAN à terme...

**Comment by tmerlier** [comment]
Nous travaillons actuellement sur une méthode de validation des adresses qui permettrait une publication partielle/progressive d'une Base adresse Locale pour répondre à ce problème.

**Comment by tmerlier** [comment]
Cette issue est résolu par une approche différente par #294
