### ISSUE TITLE
Problème d'assignation d'un numéro sur la carte

### ISSUE THREAD

**Issue by GllmR** [etalab/editeur-bal#290]
Lors de l'édition de la position d'un numéro, lorsque l'on clique sur un autre numéro, il prend la valeur du premier numéro cliqué.

---

https://user-images.githubusercontent.com/56537238/105860078-7df49180-5fed-11eb-8635-4f6a31af776f.mov

**Comment by juliencarnot** [comment]
doublon de #283

**Comment by GllmR** [comment]
Au temps pour moi 🙂
