### ISSUE TITLE
Bug d'affichage d'une limite de commune

### ISSUE THREAD

**Issue by jerbou** [etalab/editeur-bal#322]
Bonjour,

je voulais tester un autre fonctionnalité :
https://adresse.data.gouv.fr/base-adresse-nationale/89037#12.98/47.9549/3.31573

A partir de là, je n'arrive pas à voir ou s'arrete la commune de Béon et ou commence la commune sud de Montholon 
https://adresse.data.gouv.fr/base-adresse-nationale/89003#11.97/47.90152/3.322

Merci

**Comment by tmerlier** [comment]
J'ai transféré sur le bon repo 👍[ adresse.data.gouv.fr #881](https://github.com/etalab/adresse.data.gouv.fr/issues/881).
