### ISSUE TITLE
Réalisation de l'affichage fin entre adresse certifiée ou non par la commune dans le viewer ?

### ISSUE THREAD

**Issue by jerbou** [etalab/editeur-bal#323]
Bonjour,

On nous a dit à l'oreille que l'interface de consultation https://adresse.data.gouv.fr/base-adresse-nationale/

allait bientôt discriminer les adresses certifiées, des adresses non certifiés au sein même d'un BAL publiée.
Est-ce que vous avez une idée lorsque la feature sera "livrée" ?
pour le moment, c'est BAL publiée => toutes les adresses apparraissent en vert (certifiées), même si la commune n'a pas touché à des données importé BAL.

D'avance Merci,

**Comment by tmerlier** [comment]
Je me permet de fermer ce ticket, qui est malheureusement passé inaperçu (comme beaucoup…).

Cette fonctionnalité étant en ligne depuis le 6 septembre, elle permet, entre autre, de distinguer les adresses qui ont étaient sciemment validées de celles qui n'ont pas étaient touchées et publiées avec le reste. 

Les adresses des BAL déjà publiées ont donc vu leur certification se changé en "en cours de certification" et les communes ont étaient invités à certifier volontairement leurs adresses (en totalité, par voie ou une à une).

Désolé de ne pas répondu à temps… On va essayé de s'améliorer !
