### ISSUE TITLE
La propriété "voie" est mal typée lors de l'édition d'un numéro dans toponyme

### ISSUE THREAD

**Issue by GllmR** [etalab/editeur-bal#405]
Sur la page principale, dans l'onglet "toponyme", lorsque l'on édite un numéro, une erreur console apparaît : 
`Warning: Failed prop type: Invalid prop initialValue.voie of type object supplied to NumeroEditor, expected string`

Le problème vient du composant `NumeroEditor`, dans les propTypes, `voie` est typée comme "string" alors que c'est un objet. => **Uniquement lorsqu'on édite un numéro depuis l'onglet toponyme.**

Le composant attend `voie._id` qui est bien une `string`.

~~Une modification des propTypes devrait suffire à corriger le problème.~~

Le type de la propriété `initialValue.voie` n'est pas la même selon que le composant `numeroEditor` soit utilisé dans "voie" (_string_) ou dans "toponyme" (_object_)

**Comment by GllmR** [comment]
L'API-BAL ne renvoie pas le même format selon qu'on appelle `getNumeros()` ou `getNumerosToponyme()`.

_**`getNumerosToponyme()` a besoin du nom de la voie pour l'afficher et classer les numéros par voie dans la partie front.**_

Solutions possibles : 
- Modifier l'API pour qu'elle renvoie un objet "voie" et adapter la partie front
- Modifier l'API pour qu'elle renvoie une string avec l'id de la voie et faire un appel dans le front pour récupérer les noms de voie à afficher.
- Créer un autre composant `NumeroEditor` qui corresponde à l'objet renvoyé par `getNumerosToponyme()`

**Comment by tmerlier** [comment]
On peut aussi faire en sorte que les `propTypes` acceptent les deux types si c'est justifié.
