### ISSUE TITLE
Partage du droit d'édition sans effet

### ISSUE THREAD

**Issue by tmerlier** [etalab/editeur-bal#53]
Lorsque l'on ajoute une adresse email à une base locale, aucun mail n'est envoyé sur celle-ci enfin de faire parvenir un token d'édition.

- [x] Déplacer les paramètres dans un menu latéral
- [x] Corriger les bugs de soumissions des adresse
- [x] Ajouter les nouveaux collaborateur à la BAL
- [x] Créer un template de mail pour l'ajout d'un nouveau collaborateur
- [x] Envoyer un mail aux nouveaux collaborateurs

**Comment by jdesboeufs** [comment]
C'est probablement l'API qu'il faut modifier.
